project:
  type: website

website:
  title: "TSoD"
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  navbar:
    right:
      - writing.qmd
      - about.qmd
      - icon: github
        href: https://github.com/muertinho
        
format:
  html:
    theme: Litera
    css: styles.css



