---
title: "About"

about:
  template: solana

format: html
css: styles.css
image-width: 60px
image-height: 60px
comments: false
page-layout: article
---

Welcome to my website! I'm Dom, a passionate researcher with a keen interest in medical data and statistical methodologies. This blog is my space to explore concepts and share insights about the fascinating world of data science.

# My journey

My path to data science has been anything but straightforward. I began my career as a physical therapist, driven by a passion for helping people recover from injuries. While pursuing my Master’s degree in Physical Therapy, I took Biostatistics and Statistical Programming courses. Aside from realizing that I had a knack for numbers, I discovered the potential of statistics in health sciences to improve patient outcomes.

Fascinated by the opportunities of statistical modeling, I needed to solidify my foundation in programming, mathematics, and statistics. This drove me to pursue a further degree in Computational Life Science. Today, I work as a research associate, using my expertise to develop predictive models and data-driven solutions for hospitals and industry partners. In addition to research, I assist teaching classes in machine learning, signal processing, and informatics at the undergraduate level.

# What you'll find here

On this blog, you’ll find a mix of:

- **In-depth Articles:** The articles will cover the core statistical concepts: Descriptive and inferential statistics, predictive modeling, and exploratory data analysis. I am keen on working hands-on with Python and try to provide code examples when ever possible to illustrate concepts.

- **Case Studies:** Real-world examples of statistical analysis, primarily from the medical field. These case studies will demonstrate how statistical methods can be applied to solve complex problems.

- **Stats by Hand:** A series of articles where I will implement statistical concepts from scratch. This will help me and others to understand the underlying mathematics and logic behind statistical methods.


# Why this Blog

I started with this blog to provide others with insights into data science and deepen my understanding of statistical methodologies. Early on, I realized the importance of fundamental statistical concepts to adequately understand and interpret data. Through my studies, I found that I need to research and document a topic precisely to learn effectively. 

Additionaly, teaching claseIt is when I can explain a concept well enough for others to grasp that I fully understand it myself. This process often involves simplifying complex concepts into well-understandable terms.
 

*Please note that the content of this blog reflects my personal opinions and does not represent the views of my employer(s).*



